begin;
create extension if not exists pgtap;
select plan(16);
select has_table('public','client_ui_settings','F20 has client_ui_settings persistence');
select has_column('public','client_ui_settings','organization_id','F20 settings are tenant keyed');
select has_column('public','client_ui_settings','config','F20 settings have persisted config');
select has_column('public','client_ui_settings','updated_at','F20 settings have update timestamp');
select has_table('public','shipping','F21 shipping table exists');
select has_table('public','returns','F22 returns table exists');
select has_column('public','profiles','role','F10 profiles expose role');
select has_function('public','is_staff','F10 backend staff authorization function exists');
select has_table('auth','users','F13/F14 auth users exist');
select has_table('public','customer_invitations','F14 invitation persistence exists');
select has_function('public','consume_customer_invitation','F14 invitation consume function exists');
select has_table('public','customer_price_tiers','F18 customer-specific pricing tiers exist');
select has_column('public','customer_price_tiers','min_quantity','F18 MOQ is persisted');
select has_column('public','customer_price_tiers','unit_price','F18 server-side unit price exists');
select has_table('public','audit_events','F28 audit evidence persistence exists');
select has_table('public','outbox_events','F28/F12 outbox evidence persistence exists');
select * from finish();
rollback;
