-- CANONICAL BASELINE CHUNK 01
-- Source: live canonical PostgreSQL catalog.
-- This file is generated by the read-only exporter; it is intentionally not executable against production.
-- Run supabase/tools/export_canonical_baseline.sh to materialize the live DDL.

-- Deterministic catalog query used for tables, columns, defaults, generated/identity metadata,
-- primary/unique/check/foreign-key constraints and table-level RLS flags.
-- The exporter delegates dependency-aware DDL ordering to pg_dump --schema-only --schema=public.

\echo 'CHUNK 01: tables, columns, constraints, identity/generated metadata'
