-- Canonical Baseline Emitter
-- Purpose: emit executable public-schema DDL from the LIVE canonical database.
-- This is an emitter, not the baseline itself. Run against the canonical live DB with
-- an operator capable of saving the result verbatim to a .sql file.
-- Order: extensions/types -> tables -> local constraints -> foreign keys -> functions
-- -> RLS -> indexes -> triggers -> grants.
-- Safety: read-only; contains no CREATE/ALTER/DROP against the source database.

\pset tuples_only on
\pset format unaligned
\pset pager off

select '-- CANONICAL BASELINE GENERATED FROM LIVE CATALOG --';
select '-- generated_at=' || clock_timestamp()::text;
select '-- source_schema=public';

-- Extensions
select format('CREATE EXTENSION IF NOT EXISTS %I WITH SCHEMA %I;', e.extname, n.nspname)
from pg_extension e
join pg_namespace n on n.oid=e.extnamespace
where e.extname <> 'plpgsql'
order by e.extname;

-- User-defined enum types in public.
select format('CREATE TYPE public.%I AS ENUM (%s);', t.typname,
  string_agg(quote_literal(e.enumlabel), ', ' order by e.enumsortorder))
from pg_type t
join pg_namespace n on n.oid=t.typnamespace
join pg_enum e on e.enumtypid=t.oid
where n.nspname='public'
group by t.typname
order by t.typname;

-- Base tables. Preserve exact SQL type, identity, generated expression, default and nullability.
select format(E'CREATE TABLE public.%I (\n%s\n);', c.relname,
  string_agg(
    format('  %I %s%s%s%s%s',
      a.attname,
      pg_catalog.format_type(a.atttypid, a.atttypmod),
      case when a.attidentity='a' then ' GENERATED ALWAYS AS IDENTITY' when a.attidentity='d' then ' GENERATED BY DEFAULT AS IDENTITY' else '' end,
      case when a.attgenerated='s' then ' GENERATED ALWAYS AS (' || pg_get_expr(ad.adbin, ad.adrelid) || ') STORED' else '' end,
      case when a.attgenerated='' and ad.adbin is not null and a.attidentity='' then ' DEFAULT ' || pg_get_expr(ad.adbin, ad.adrelid) else '' end,
      case when a.attnotnull then ' NOT NULL' else '' end
    ), E',\n' order by a.attnum))
from pg_class c
join pg_namespace n on n.oid=c.relnamespace
join pg_attribute a on a.attrelid=c.oid and a.attnum>0 and not a.attisdropped
left join pg_attrdef ad on ad.adrelid=a.attrelid and ad.adnum=a.attnum
where n.nspname='public' and c.relkind='r'
group by c.oid,c.relname
order by c.relname;

-- Primary/unique/check constraints.
select format('ALTER TABLE public.%I ADD CONSTRAINT %I %s;', c.relname, con.conname, pg_get_constraintdef(con.oid, true))
from pg_constraint con
join pg_class c on c.oid=con.conrelid
join pg_namespace n on n.oid=c.relnamespace
where n.nspname='public' and con.contype in ('p','u','c')
order by c.relname, con.conname;

-- Foreign keys after all base tables and local constraints.
select format('ALTER TABLE public.%I ADD CONSTRAINT %I %s;', c.relname, con.conname, pg_get_constraintdef(con.oid, true))
from pg_constraint con
join pg_class c on c.oid=con.conrelid
join pg_namespace n on n.oid=c.relnamespace
where n.nspname='public' and con.contype='f'
order by c.relname, con.conname;

-- Exact function definitions.
select pg_get_functiondef(p.oid) || E'\n'
from pg_proc p
join pg_namespace n on n.oid=p.pronamespace
where n.nspname='public' and p.prokind='f'
order by p.proname, pg_get_function_identity_arguments(p.oid), p.oid;

-- RLS enablement.
select format('ALTER TABLE public.%I ENABLE ROW LEVEL SECURITY;', c.relname)
from pg_class c
join pg_namespace n on n.oid=c.relnamespace
where n.nspname='public' and c.relkind='r' and c.relrowsecurity
order by c.relname;

-- RLS policies: preserve command, roles, USING and WITH CHECK expressions.
select format('CREATE POLICY %I ON public.%I AS %s FOR %s TO %s%s%s;',
  pol.polname, c.relname,
  case when pol.polpermissive then 'PERMISSIVE' else 'RESTRICTIVE' end,
  case pol.polcmd when 'r' then 'SELECT' when 'a' then 'INSERT' when 'w' then 'UPDATE' when 'd' then 'DELETE' else 'ALL' end,
  coalesce((select string_agg(quote_ident(r.rolname), ', ' order by r.rolname) from pg_roles r where r.oid=any(pol.polroles)), 'PUBLIC'),
  case when pol.polqual is not null then ' USING (' || pg_get_expr(pol.polqual, pol.polrelid) || ')' else '' end,
  case when pol.polwithcheck is not null then ' WITH CHECK (' || pg_get_expr(pol.polwithcheck, pol.polrelid) || ')' else '' end)
from pg_policy pol
join pg_class c on c.oid=pol.polrelid
join pg_namespace n on n.oid=c.relnamespace
where n.nspname='public'
order by c.relname, pol.polname;

-- Non-constraint indexes. PK/UNIQUE indexes are already created by their constraints.
select pg_get_indexdef(i.indexrelid) || ';'
from pg_index i
join pg_class ic on ic.oid=i.indexrelid
join pg_class tc on tc.oid=i.indrelid
join pg_namespace n on n.oid=tc.relnamespace
where n.nspname='public'
  and not exists (select 1 from pg_constraint con where con.conindid=i.indexrelid)
order by tc.relname, ic.relname;

-- Exact trigger definitions. pg_get_triggerdef is authoritative and executable.
select regexp_replace(pg_get_triggerdef(t.oid, true), ';?$', ';')
from pg_trigger t
join pg_class c on c.oid=t.tgrelid
join pg_namespace n on n.oid=c.relnamespace
where n.nspname='public' and not t.tgisinternal
order by c.relname, t.tgname;

-- Table grants. information_schema presents normalized explicit grants.
select format('GRANT %s ON TABLE public.%I TO %I;',
  string_agg(privilege_type, ', ' order by privilege_type), table_name, grantee)
from information_schema.role_table_grants
where table_schema='public'
group by table_name, grantee
order by table_name, grantee;

-- Sequence grants. Filter the usage view to sequence objects.
select format('GRANT %s ON SEQUENCE public.%I TO %I;',
  string_agg(privilege_type, ', ' order by privilege_type), object_name, grantee)
from information_schema.role_usage_grants
where object_schema='public' and object_type='SEQUENCE'
group by object_name, grantee
order by object_name, grantee;

-- Function EXECUTE grants with exact overloaded signatures.
select format('GRANT EXECUTE ON FUNCTION public.%I(%s) TO %s;',
  p.proname,
  pg_get_function_identity_arguments(p.oid),
  case when x.grantee=0 then 'PUBLIC' else quote_ident(r.rolname) end)
from pg_proc p
join pg_namespace n on n.oid=p.pronamespace
cross join lateral aclexplode(coalesce(p.proacl, acldefault('f', p.proowner))) x
left join pg_roles r on r.oid=x.grantee
where n.nspname='public'
  and p.prokind='f'
  and x.privilege_type='EXECUTE'
  and x.grantee <> p.proowner
order by p.proname, pg_get_function_identity_arguments(p.oid), x.grantee;

select '-- END CANONICAL BASELINE --';
