import { useCallback, useEffect, useMemo, useState, type FormEvent } from 'react';
import type { CartLine, Product } from './domain/types';
import { calculateClientPreviewTotal } from './domain/order';
import { formatMoney } from './domain/pricing';
import { getCatalog, getProductImageUrls, type CatalogItem } from './services/catalog';
import { getCategories, type CategoryOption } from './services/categories';
import { getCart, removeCartItem, setCartItem } from './services/cart';
import { createOrder } from './services/orders';
import type { CustomerOrderSummary } from './services/customerOrders';
import { listCustomerInvoices, type CustomerInvoice } from './services/customerInvoices';
import { createOrderTemplate, deleteOrderTemplate, listOrderTemplates, type OrderTemplate } from './services/orderTemplates';
import { parseQuickOrderWorkbook, validateQuickOrderRows, type QuickOrderDiagnostic } from './services/customerQuickOrder';
import { listCustomerPayments, type CustomerPayment } from './services/customerPayments';
import { getSession, signIn, signOut } from './services/auth';
import { supabase } from './lib/supabase';
import AdminPanel from './AdminPanel';
import './styles.css';
import './customer-portal-v3.css';
import './customer-portal-v3-dynamic.css';

type UserRole = 'owner' | 'admin' | 'sales' | 'warehouse' | 'viewer' | 'customer';
const STAFF_ROLES = new Set<UserRole>(['owner', 'admin', 'sales', 'warehouse']);
type PriceTier = { min_quantity: number; unit_price: number; currency: string };
type Finance = { currency: string; creditLimit: number; outstanding: number; available: number; entries: Array<{ id: string; reference?: string; description: string; debit: number; credit: number; due_date?: string; status: string; created_at: string }> };
type ClientUiConfig = { showSearch:boolean; showCategories:boolean; showExcel:boolean; showCredit:boolean; showTemplates:boolean; showInventory:boolean; showRetailPrice:boolean; showQuickOrder:boolean; requireQuantityConfirmation:boolean; showTieredPricing:boolean; showSavingsCalculator:boolean; showImageSearch:boolean; showVoiceSearch:boolean; showPaymentMethods:boolean; paymentOnCredit:boolean; paymentCash:boolean; paymentTransfer:boolean; minOrderValue:number; maxOrderValue:number; maxTemplates:number; };
const DEFAULT_UI_CONFIG: ClientUiConfig = { showSearch:true, showCategories:true, showExcel:true, showCredit:true, showTemplates:true, showInventory:true, showRetailPrice:false, showQuickOrder:true, requireQuantityConfirmation:true, showTieredPricing:true, showSavingsCalculator:true, showImageSearch:false, showVoiceSearch:false, showPaymentMethods:true, paymentOnCredit:true, paymentCash:true, paymentTransfer:true, minOrderValue:0, maxOrderValue:0, maxTemplates:50 };
const PAYMENT_OPTIONS = [{key:'credit' as const,label:'آجل / ائتمان',field:'paymentOnCredit' as const},{key:'cash' as const,label:'نقدي',field:'paymentCash' as const},{key:'transfer' as const,label:'حوالة',field:'paymentTransfer' as const}];
const PAYMENT_LABELS:Record<string,string>={credit:'آجل / ائتمان',cash:'نقدي',transfer:'حوالة'};
function mapProduct(item: CatalogItem, categoryName: string, imageUrl?: string): Product { return { id:item.id, sku:item.sku, name:item.name, unit:item.unit, category:categoryName, description:item.description ?? undefined, availableQuantity:item.available_quantity, status:item.status === 'active' ? 'active' : 'inactive', imageUrl }; }
function money(value:number,currency='YER'){return `${formatMoney(value)} ${currency==='YER'?'ر.ي':currency}`;}

export default function AppV3Fixed(){
  const [email,setEmail]=useState(''); const [password,setPassword]=useState(''); const [signedIn,setSignedIn]=useState(false); const [ready,setReady]=useState(false); const [role,setRole]=useState<UserRole>('viewer'); const [customerId,setCustomerId]=useState<string|null>(null); const [organizationId,setOrganizationId]=useState<string|null>(null); const [warehouseId,setWarehouseId]=useState<string|null>(null); const [customerName,setCustomerName]=useState('تاجر الأغبري'); const [customerPhone,setCustomerPhone]=useState<string|null>(null); const [customerTier,setCustomerTier]=useState<string>('wholesale');
  const [config,setConfig]=useState<ClientUiConfig>(DEFAULT_UI_CONFIG); const [query,setQuery]=useState(''); const [categoryId,setCategoryId]=useState<string|null>(null); const [categories,setCategories]=useState<CategoryOption[]>([]); const [products,setProducts]=useState<Product[]>([]); const [tiers,setTiers]=useState<Record<string,PriceTier[]>>({}); const [cart,setCart]=useState<CartLine[]>([]); const [cartOpen,setCartOpen]=useState(false); const [quickOpen,setQuickOpen]=useState(false); const [section,setSection]=useState<'dashboard'|'catalog'|'orders'|'finance'|'templates'|'invoices'|'account'>('dashboard');
  const [orders,setOrders]=useState<CustomerOrderSummary[]>([]); const [finance,setFinance]=useState<Finance|null>(null); const [invoices,setInvoices]=useState<CustomerInvoice[]>([]); const [payments,setPayments]=useState<CustomerPayment[]>([]); const [selectedInvoice,setSelectedInvoice]=useState<string|null>(null); const [templates,setTemplates]=useState<OrderTemplate[]>([]); const [templateName,setTemplateName]=useState(''); const [confirmed,setConfirmed]=useState<Record<string,boolean>>({}); const [payment,setPayment]=useState<'credit'|'cash'|'transfer'>('credit'); const [loading,setLoading]=useState(false); const [busy,setBusy]=useState(false); const [message,setMessage]=useState(''); const [error,setError]=useState('');
  const loadConfig=useCallback(async(orgId:string)=>{ if(!supabase)return; const {data}=await supabase.from('client_ui_settings').select('config').eq('organization_id',orgId).maybeSingle(); setConfig(data?.config?{...DEFAULT_UI_CONFIG,...(data.config as Partial<ClientUiConfig>)}:DEFAULT_UI_CONFIG); },[]);
  const loadIdentity=useCallback(async(userId:string)=>{if(!supabase)return;const {data,error:profileError}=await supabase.from('profiles').select('customer_id,role,organization_id').eq('id',userId).single();if(profileError)throw profileError;setRole((data?.role as UserRole)??'viewer');setCustomerId(data?.customer_id??null);setOrganizationId(data?.organization_id??null);if(data?.organization_id){await loadConfig(data.organization_id);const {data:warehouse}=await supabase.from('warehouses').select('id').eq('organization_id',data.organization_id).eq('is_active',true).order('created_at').limit(1).maybeSingle();setWarehouseId(warehouse?.id??null);}if(data?.customer_id){const {data:customer}=await supabase.from('customers').select('name,phone,tier').eq('id',data.customer_id).maybeSingle();if(customer?.name)setCustomerName(customer.name);setCustomerPhone(customer?.phone??null);setCustomerTier(String(customer?.tier??'wholesale'));setTemplates(await listOrderTemplates(data.customer_id));}},[loadConfig]);
  useEffect(()=>{let dead=false;void getSession().then(async s=>{if(dead)return;setSignedIn(Boolean(s));setReady(true);if(s)await loadIdentity(s.user.id);}).catch(e=>{if(!dead){setReady(true);setError(e instanceof Error?e.message:'تعذر قراءة الجلسة.');}});const sub=supabase?.auth.onAuthStateChange((event,s)=>{if(dead)return;setSignedIn(Boolean(s));if(s&&(event==='SIGNED_IN'||event==='TOKEN_REFRESHED'))void loadIdentity(s.user.id);if(!s){setCustomerId(null);setOrganizationId(null);setWarehouseId(null);setRole('viewer');setProducts([]);setCart([]);setFinance(null);setOrders([]);setInvoices([]);setPayments([]);setTemplates([]);setConfig(DEFAULT_UI_CONFIG);}});return()=>{dead=true;sub?.data.subscription.unsubscribe();};},[loadIdentity]);
  useEffect(()=>{if(!signedIn||!organizationId||!supabase)return;const channel=supabase.channel(`b2b-ui-${organizationId}`).on('postgres_changes',{event:'*',schema:'public',table:'client_ui_settings',filter:`organization_id=eq.${organizationId}`},()=>void loadConfig(organizationId)).subscribe();const timer=window.setInterval(()=>void loadConfig(organizationId),15000);return()=>{supabase.removeChannel(channel);window.clearInterval(timer);};},[signedIn,organizationId,loadConfig]);
  const loadData=useCallback(async()=>{if(!signedIn||!customerId||!supabase)return;setLoading(true);setError('');try{const [items,saved,cats,customerInvoices,customerPayments]=await Promise.all([getCatalog(query,categoryId,60,0,warehouseId??undefined),getCart(),getCategories(),listCustomerInvoices(customerId),listCustomerPayments()]);const cmap=new Map(cats.map(c=>[c.id,c.name]));const urls=await getProductImageUrls(items.map(i=>i.image_path));const mapped=items.map(i=>mapProduct(i,cmap.get(i.category_id??'')??'أصناف',i.image_path?urls.get(i.image_path):undefined));setProducts(mapped);setCategories(cats);setCart(saved.map(i=>{const p=mapped.find(x=>x.id===i.product_id)??({id:i.product_id,sku:i.sku,name:i.name,unit:i.unit,category:'أصناف',availableQuantity:0,status:'active'} as Product);return{product:p,quantity:i.quantity,unitPrice:i.authorized_price??0};}));setInvoices(customerInvoices);setPayments(customerPayments);if(items.length){const {data:rows}=await supabase.from('customer_price_tiers').select('product_id,min_quantity,unit_price,currency').eq('customer_id',customerId).in('product_id',items.map(i=>i.id)).order('min_quantity');const grouped:Record<string,PriceTier[]>={};for(const row of rows??[])(grouped[row.product_id]??=[]).push({min_quantity:Number(row.min_quantity),unit_price:Number(row.unit_price),currency:row.currency});setTiers(grouped);}const [{data:orderRows},{data:account},{data:ledger}]=await Promise.all([supabase.from('orders').select('id,order_number,total,currency,status,created_at').eq('customer_id',customerId).order('created_at',{ascending:false}).limit(30),supabase.from('customer_credit_accounts').select('currency,credit_limit,outstanding_balance,available_credit').eq('customer_id',customerId).maybeSingle(),supabase.from('customer_ledger_entries').select('id,reference,description,debit,credit,due_date,status,created_at').eq('customer_id',customerId).order('created_at',{ascending:false}).limit(50)]);setOrders((orderRows??[]) as CustomerOrderSummary[]);setFinance(account?{currency:account.currency,creditLimit:Number(account.credit_limit),outstanding:Number(account.outstanding_balance),available:Number(account.available_credit),entries:(ledger??[]).map(e=>({...e,debit:Number(e.debit),credit:Number(e.credit)}))}:null);}catch(e){setError(e instanceof Error?e.message:'تعذر تحميل المتجر.');}finally{setLoading(false);}},[signedIn,customerId,warehouseId,query,categoryId]);
  useEffect(()=>{void loadData();},[loadData]);
  const total=calculateClientPreviewTotal(cart);const cartCount=cart.reduce((s,l)=>s+l.quantity,0);const categoriesView=useMemo(()=>[{id:null,name:'الكل'},...categories],[categories]);
  function effectivePrice(p:Product,q:number){const list=tiers[p.id]??[];return [...list].sort((a,b)=>b.min_quantity-a.min_quantity).find(x=>q>=x.min_quantity)?.unit_price??0;}
  function nextTier(p:Product,q:number){return (tiers[p.id]??[]).filter(x=>x.min_quantity>q).sort((a,b)=>a.min_quantity-b.min_quantity)[0];}
  function setQtyConfirmed(id:string,value:boolean){setConfirmed(c=>({...c,[id]:value}));}
  function navigate(next:typeof section){if(next!==section&&config.requireQuantityConfirmation&&cart.some(l=>!confirmed[l.product.id])){setError('اعتمد كميات السلة أولاً قبل الانتقال إلى قسم آخر.');setCartOpen(true);return;}setError('');setSection(next);}
  async function add(p:Product,q=1){const price=effectivePrice(p,q);if(price<=0)return setError('لا يوجد سعر مصرح به لهذا الصنف.');if(q<1||q>p.availableQuantity)return setError('الكمية المطلوبة غير متاحة.');const existing=cart.find(l=>l.product.id===p.id);const next=Math.min((existing?.quantity??0)+q,p.availableQuantity);try{await setCartItem(p.id,next);setCart(c=>existing?c.map(l=>l.product.id===p.id?{...l,quantity:next,unitPrice:effectivePrice(p,next)}:l):[...c,{product:p,quantity:next,unitPrice:price}]);setQtyConfirmed(p.id,!config.requireQuantityConfirmation);setCartOpen(true);setError('');}catch(e){setError(e instanceof Error?e.message:'تعذر تحديث السلة.');}}
  async function update(id:string,q:number){const line=cart.find(l=>l.product.id===id);if(!line)return;const next=Math.max(0,Math.min(q,line.product.availableQuantity));try{if(!next){await removeCartItem(id);setCart(c=>c.filter(l=>l.product.id!==id));setConfirmed(c=>{const n={...c};delete n[id];return n;});}else{await setCartItem(id,next);setCart(c=>c.map(l=>l.product.id===id?{...l,quantity:next,unitPrice:effectivePrice(l.product,next)}:l));setQtyConfirmed(id,!config.requireQuantityConfirmation);}}catch(e){setError(e instanceof Error?e.message:'تعذر تحديث الكمية.');}}
  async function submit(){if(!customerId||!cart.length||busy)return;if(config.requireQuantityConfirmation&&cart.some(l=>!confirmed[l.product.id]))return setError('يجب اعتماد جميع الكميات قبل إرسال الطلب.');if(config.minOrderValue>0&&total<config.minOrderValue)return setError(`الحد الأدنى للطلب ${money(config.minOrderValue)}.`);if(config.maxOrderValue>0&&total>config.maxOrderValue)return setError(`الحد الأعلى للطلب ${money(config.maxOrderValue)}.`);if(config.showPaymentMethods&&!PAYMENT_OPTIONS.some(x=>x.key===payment&&config[x.field]))return setError('وسيلة الدفع المختارة غير متاحة حاليًا.');setBusy(true);setError('');try{const result=await createOrder({customerId,idempotencyKey:crypto.randomUUID(),lines:cart.map(l=>({productId:l.product.id,quantity:l.quantity}))},warehouseId??undefined);setCart([]);setConfirmed({});setCartOpen(false);setMessage(`تم إرسال الطلب #${result.order_number} بنجاح.`);setSection('orders');void loadData();}catch(e){setError(e instanceof Error?e.message:'تعذر إرسال الطلب.');}finally{setBusy(false);}}
  async function saveTemplate(){if(!customerId||!cart.length||!templateName.trim())return;if(templates.length>=config.maxTemplates)return setError('تم بلوغ الحد الأعلى للقوائم المحدد من الإدارة.');setBusy(true);setError('');try{const item=await createOrderTemplate({customerId,name:templateName,branchLabel:'الفرع الرئيسي',lines:cart.map(l=>({productId:l.product.id,sku:l.product.sku,name:l.product.name,unit:l.product.unit,quantity:l.quantity}))});setTemplates(t=>[item,...t]);setTemplateName('');setMessage('تم حفظ قائمة الطلب في قاعدة البيانات.');}catch(e){setError(e instanceof Error?e.message:'تعذر حفظ قائمة الطلب.');}finally{setBusy(false);}}
  async function removeTemplate(id:string){if(!customerId)return;try{await deleteOrderTemplate(id,customerId);setTemplates(t=>t.filter(x=>x.id!==id));setMessage('تم حذف قائمة الطلب.');}catch(e){setError(e instanceof Error?e.message:'تعذر حذف قائمة الطلب.');}}
  async function applyTemplate(t:OrderTemplate){setBusy(true);setError('');try{for(const l of t.lines){let p=products.find(x=>x.id===l.productId);if(!p&&supabase){const {data}=await supabase.from('products').select('id,sku,name,unit,description,status,category_id').eq('id',l.productId).maybeSingle();if(data){const cat=categories.find(c=>c.id===data.category_id);const catalog=await getCatalog(data.sku,null,5,0,warehouseId??undefined);const item=catalog.find(x=>x.id===data.id)||catalog[0];if(item)p=mapProduct(item,cat?.name??'أصناف');}}if(!p)throw new Error(`الصنف ${l.sku} غير متاح حاليًا.`);await add(p,Math.min(l.quantity,p.availableQuantity));}navigate('catalog');}catch(e){setError(e instanceof Error?e.message:'تعذر تطبيق قائمة الطلب.');}finally{setBusy(false);}}
  function downloadStatement(){if(!finance)return;const rows=[['المرجع','البيان','مدين','دائن','الاستحقاق','الحالة'],...finance.entries.map(e=>[e.reference??'-',e.description,String(e.debit),String(e.credit),e.due_date??'-',e.status])];const csv='\ufeff'+rows.map(r=>r.map(c=>`"${String(c).replaceAll('"','""')}"`).join(',')).join('\n');const url=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=`aghbari-statement-${new Date().toISOString().slice(0,10)}.csv`;a.click();URL.revokeObjectURL(url);}
  async function login(e:FormEvent){e.preventDefault();setBusy(true);setError('');try{const s=await signIn(email,password);if(s)await loadIdentity(s.user.id);}catch(e){setError(e instanceof Error?e.message:'تعذر تسجيل الدخول.');}finally{setBusy(false);}}
  async function logout(){await signOut();}
  if(!ready)return <div className="customer-shell"><div className="portal-loading">جارٍ تجهيز بوابة الأغبري…</div></div>;
  if(!signedIn)return <div className="customer-shell auth-shell"><div className="auth-card"><span className="eyebrow">AGHBARI B2B</span><h1>بوابة الأغبري التجارية</h1><p>شراء جملة سريع، أسعار مصرح بها، ومتابعة مالية وتشغيلية في مكان واحد.</p><form onSubmit={login}><input value={email} onChange={e=>setEmail(e.target.value)} type="email" placeholder="البريد الإلكتروني" required/><input value={password} onChange={e=>setPassword(e.target.value)} type="password" placeholder="كلمة المرور" required/><button disabled={busy}>{busy?'جارٍ الدخول…':'دخول آمن'}</button></form>{error&&<div className="error-banner">{error}</div>}</div></div>;
  if(STAFF_ROLES.has(role))return <><header className="staff-topbar"><strong>بوابة الأغبري · مركز الإدارة</strong><button onClick={()=>void logout()}>خروج</button></header><AdminPanel role={role as 'owner'|'admin'|'sales'|'warehouse'|'viewer'}/></>;
  return <div className="customer-shell"><header className="portal-header"><div><span className="eyebrow">B2B ENTERPRISE</span><h1>بوابة الأغبري</h1><small>مرحبًا، {customerName}</small></div><div className="header-actions"><span className="connection">● متصل</span><button onClick={()=>setCartOpen(true)}>السلة <b>{cartCount}</b></button><button className="ghost" onClick={()=>void logout()}>خروج</button></div></header>
    <div className="portal-body"><aside className="portal-nav"><button className={section==='dashboard'?'active':''} onClick={()=>navigate('dashboard')}>الرئيسية</button><button className={section==='catalog'?'active':''} onClick={()=>navigate('catalog')}>الكتالوج</button><button className={section==='orders'?'active':''} onClick={()=>navigate('orders')}>طلباتي</button>{config.showTemplates&&<button className={section==='templates'?'active':''} onClick={()=>navigate('templates')}>قوائم الطلب</button>}<button className={section==='invoices'?'active':''} onClick={()=>navigate('invoices')}>الفواتير</button>{config.showCredit&&<button className={section==='finance'?'active':''} onClick={()=>navigate('finance')}>المركز المالي</button>}<button className={section==='account'?'active':''} onClick={()=>navigate('account')}>حسابي</button></aside><main className="portal-main">
      {section==='dashboard'&&<section className="content-card"><div className="hero-card"><div><span className="eyebrow">لوحة العميل</span><h2>مرحبًا بك، {customerName}</h2><p>تابع مشترياتك، مخزونك المتاح، مركزك المالي، وفواتيرك من مكان واحد.</p></div><div className="hero-stat"><strong>{cartCount}</strong><span>قطعة في السلة</span></div></div><div className="finance-grid"><div><small>الطلبات</small><strong>{orders.length}</strong></div><div><small>الفواتير</small><strong>{invoices.length}</strong></div><div><small>المستحق</small><strong>{finance?money(finance.outstanding,finance.currency):'—'}</strong></div><div><small>المتاح للشراء</small><strong>{finance?money(finance.available,finance.currency):'—'}</strong></div></div><div className="section-title"><div><span className="eyebrow">آخر نشاط</span><h2>أحدث الطلبات</h2></div><button className="ghost" onClick={()=>navigate('orders')}>عرض الكل</button></div>{orders.length?<div className="orders-list">{orders.slice(0,5).map(o=><article className="order-card" key={o.id}><div className="order-head"><strong>طلب #{o.order_number}</strong><strong>{money(o.total,o.currency)}</strong></div><small>{new Date(o.created_at).toLocaleString('ar-YE')}</small><div className="order-status">{o.status}</div></article>)}</div>:<div className="empty-state">لا توجد طلبات بعد. ابدأ من الكتالوج.</div>}</section>}
      {section==='catalog'&&<><section className="hero-card"><div><span className="eyebrow">تجارة جملة أسرع</span><h2>احتياج متجرك، في طلب واحد.</h2><p>ابحث بالاسم أو SKU أو الباركود، راجع شرائح السعر، ثم اعتمد الكميات وأرسل الطلب.</p></div><div className="hero-stat"><strong>{products.length}</strong><span>صنف متاح</span></div></section>
      {config.showSearch&&<section className="search-panel"><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="ابحث باسم الصنف، SKU أو الباركود…" aria-label="البحث في الكتالوج"/><div>{config.showVoiceSearch&&<button title="البحث الصوتي">🎙</button>}{config.showImageSearch&&<button title="البحث بالصور">⌕</button>}{config.showExcel&&<button onClick={()=>setQuickOpen(true)}>رفع Excel</button>}{config.showQuickOrder&&<button onClick={()=>setQuickOpen(true)}>طلب سريع</button>}</div></section>}
      {config.showCategories&&<div className="category-row">{categoriesView.map(c=><button key={c.id??'all'} className={categoryId===c.id?'active':''} onClick={()=>setCategoryId(c.id)}>{c.name}</button>)}</div>}
      {loading?<div className="portal-loading">جارٍ تحميل الكتالوج…</div>:<div className="product-grid">{products.map(p=>{const q=cart.find(l=>l.product.id===p.id)?.quantity??0;const baseQty=Math.max(1,q);const price=effectivePrice(p,baseQty);const next=nextTier(p,baseQty);return <article className="product-card" key={p.id}>{p.imageUrl?<img src={p.imageUrl} alt=""/>:<div className="product-placeholder">{p.name.slice(0,1)}</div>}<div className="product-body"><span className="sku">{p.sku}</span><h3>{p.name}</h3><small>{p.category} · {p.unit}</small>{config.showInventory&&<span className="stock">{p.availableQuantity>0?`متاح ${p.availableQuantity} ${p.unit}`:'غير متوفر'}</span>}{price>0?<div className="price-row"><strong>{money(price)}</strong>{config.showRetailPrice&&<small>سعر التجزئة متاح حسب الصلاحية</small>}</div>:<div className="price-hidden">السعر حسب حسابك</div>}{config.showTieredPricing&&(tiers[p.id]??[]).length>1&&<div className="tiers">{(tiers[p.id]??[]).map(t=><span key={t.min_quantity}>من {t.min_quantity}: {money(t.unit_price,t.currency)}</span>)}</div>}{config.showSavingsCalculator&&next&&<div className="saving">أضف {next.min_quantity-baseQty} {p.unit} للوصول إلى {money(next.unit_price,next.currency)}</div>}<button className="add-button" disabled={p.availableQuantity<1||price<=0} onClick={()=>void add(p)}>إضافة للسلة</button></div></article>})}</div>}
      </>}
      {section==='orders'&&<section className="content-card"><div className="section-title"><div><span className="eyebrow">التشغيل</span><h2>طلباتك وشحناتك</h2></div><span>{orders.length} طلب</span></div>{orders.length?<div className="orders-list">{orders.map(o=><article className="order-card" key={o.id}><div className="order-head"><strong>طلب #{o.order_number}</strong><strong>{money(o.total,o.currency)}</strong></div><small>{new Date(o.created_at).toLocaleString('ar-YE')}</small><div className="order-status">{o.status}</div><button onClick={async()=>{const {data}=await supabase.from('order_items').select('product_id,quantity').eq('order_id',o.id);for(const x of data??[]){const p=products.find(y=>y.id===x.product_id);if(p)await add(p,Math.min(Number(x.quantity),p.availableQuantity));}navigate('catalog');}}>إعادة الطلب</button></article>)}</div>:<div className="empty-state">لا توجد طلبات سابقة بعد.</div>}</section>}
      {section==='templates'&&config.showTemplates&&<section className="content-card"><div className="section-title"><div><span className="eyebrow">طلبات دورية</span><h2>قوائم الطلب المحفوظة</h2></div><span>{templates.length}/{config.maxTemplates}</span></div><div className="template-save"><input value={templateName} onChange={e=>setTemplateName(e.target.value)} placeholder="اسم القائمة"/><button disabled={!templateName.trim()||!cart.length||busy} onClick={()=>void saveTemplate()}>حفظ السلة كقائمة</button></div><div className="template-grid">{templates.map(t=><article className="template-card" key={t.id}><strong>{t.name}</strong><small>{t.lines.length} أصناف · {new Date(t.updatedAt).toLocaleDateString('ar-YE')}</small><div><button disabled={busy} onClick={()=>void applyTemplate(t)}>إضافة للسلة</button><button className="ghost" disabled={busy} onClick={()=>void removeTemplate(t.id)}>حذف</button></div></article>)}</div>{!templates.length&&<div className="empty-state">لا توجد قوائم محفوظة. احفظ السلة لتظهر هنا بعد تسجيل الدخول مرة أخرى.</div>}</section>}
      {section==='invoices'&&<section className="content-card"><div className="section-title"><div><span className="eyebrow">المستندات المالية</span><h2>فواتيرك</h2></div><span>{invoices.length} فاتورة</span></div>{selectedInvoice?(()=>{const inv=invoices.find(x=>x.id===selectedInvoice);if(!inv)return <div className="empty-state">الفاتورة غير موجودة.</div>;return <div className="invoice-detail"><button className="ghost" onClick={()=>setSelectedInvoice(null)}>← العودة للفواتير</button><div className="invoice-summary"><div><small>رقم الفاتورة</small><strong>#{inv.invoiceNumber}</strong></div><div><small>التاريخ</small><strong>{new Date(inv.createdAt).toLocaleDateString('ar-YE')}</strong></div><div><small>الحالة</small><strong>{inv.status}</strong></div><div><small>الإجمالي</small><strong>{money(inv.total,inv.currency)}</strong></div></div><div className="invoice-items">{inv.items.map(item=><div className="ledger-row" key={item.id}><span>{item.quantity} ×</span><strong>{item.description}</strong><span>{money(item.unitPrice,inv.currency)}</span><span>{item.lineTotal==null?'—':money(item.lineTotal,inv.currency)}</span></div>)}</div><div className="drawer-total"><span>حالة الدفع</span><strong>{inv.status==='paid'?'مدفوعة':inv.status==='partially_paid'?'مدفوعة جزئيًا':'غير مدفوعة'}</strong></div></div>;})():invoices.length?<div className="orders-list">{invoices.map(inv=><article className="order-card" key={inv.id}><div className="order-head"><strong>فاتورة #{inv.invoiceNumber}</strong><strong>{money(inv.total,inv.currency)}</strong></div><small>{new Date(inv.createdAt).toLocaleDateString('ar-YE')} · مرتبطة بالطلب #{inv.orderId.slice(0,8)}</small><div className="order-status">{inv.status}</div><button onClick={()=>setSelectedInvoice(inv.id)}>عرض التفاصيل</button></article>)}</div>:<div className="empty-state">لا توجد فواتير متاحة لهذا الحساب.</div>}</section>}
      {section==='finance'&&config.showCredit&&<section className="content-card"><div className="section-title"><div><span className="eyebrow">الثقة المالية</span><h2>المركز المالي</h2></div><button onClick={downloadStatement} disabled={!finance}>تنزيل الكشف</button></div>{finance?<><div className="finance-grid"><div><small>الحد الائتماني</small><strong>{money(finance.creditLimit,finance.currency)}</strong></div><div><small>الرصيد المستحق</small><strong>{money(finance.outstanding,finance.currency)}</strong></div><div><small>المتاح للشراء</small><strong>{money(finance.available,finance.currency)}</strong></div></div><div className="ledger-table">{finance.entries.map(e=><div className="ledger-row" key={e.id}><span>{e.reference??'—'}</span><strong>{e.description}</strong><span>{e.debit?`مدين ${money(e.debit,finance.currency)}`:`دائن ${money(e.credit,finance.currency)}`}</span><span>{e.due_date??'—'}</span></div>)}</div></>:<div className="empty-state">لا توجد بيانات مركز مالي متاحة.</div>}<div className="section-title"><div><span className="eyebrow">المدفوعات</span><h2>سجل المدفوعات</h2></div><span>{payments.length} عملية</span></div>{payments.length?<div className="ledger-table">{payments.map(p=><div className="ledger-row" key={p.id}><span>{new Date(p.paidAt??p.createdAt).toLocaleDateString('ar-YE')}</span><strong>{PAYMENT_LABELS[p.method]??p.method}</strong><span>{money(p.amount,finance?.currency??'YER')}</span><span>{p.reference??'—'}</span></div>)}</div>:<div className="empty-state">لا توجد مدفوعات مسجلة لهذا الحساب.</div>}</section>}
      {section==='account'&&<section className="content-card"><div className="section-title"><div><span className="eyebrow">الحساب</span><h2>بيانات الشركة / الحساب</h2></div><span className="connection">● متصل</span></div><div className="finance-grid"><div><small>اسم العميل</small><strong>{customerName}</strong></div><div><small>الهاتف</small><strong>{customerPhone??'غير مسجل'}</strong></div><div><small>فئة العميل</small><strong>{customerTier==='distributor'?'موزع':customerTier==='retail'?'تجزئة':'جملة'}</strong></div><div><small>معرف المؤسسة</small><strong>{organizationId?`${organizationId.slice(0,8)}…`:'—'}</strong></div></div><div className="empty-state">تعديل بيانات الحساب يتم من مركز الإدارة حفاظًا على مصدر الحقيقة والصلاحيات.</div></section>}
      {error&&<div className="error-banner" role="alert">{error}</div>}{message&&<div className="success" role="status">{message}</div>}
    </main></div>
    {quickOpen&&config.showQuickOrder&&<div className="modal-backdrop" onClick={()=>setQuickOpen(false)}><section className="modal" onClick={e=>e.stopPropagation()}><div className="modal-head"><h2>الطلب السريع</h2><button onClick={()=>setQuickOpen(false)}>×</button></div><p>ارفع XLSX أو أدخل SKU والكمية. لن تُضاف أي سطور قبل التحقق منها.</p><QuickOrder products={products} onAddMany={async(items)=>{for(const item of items)await add(item.product,item.quantity);}}/></section></div>}
    {cartOpen&&<div className="drawer-backdrop" onClick={()=>setCartOpen(false)}><aside className="cart-drawer" onClick={e=>e.stopPropagation()}><div className="drawer-head"><h2>السلة · {cartCount}</h2><button onClick={()=>setCartOpen(false)}>×</button></div>{cart.map(l=>{const next=nextTier(l.product,l.quantity);return <div className="drawer-line" key={l.product.id}><div><strong>{l.product.name}</strong><small>{money(l.unitPrice)} / {l.product.unit}</small>{config.showSavingsCalculator&&next&&<small className="saving">تبقى {next.min_quantity-l.quantity} للوصول للسعر التالي</small>}</div><div className="quantity"><button onClick={()=>void update(l.product.id,l.quantity-1)}>−</button><span>{l.quantity}</span><button onClick={()=>void update(l.product.id,l.quantity+1)}>+</button></div>{config.requireQuantityConfirmation&&<button className={confirmed[l.product.id]?'confirmed':'confirm'} onClick={()=>setQtyConfirmed(l.product.id,!confirmed[l.product.id])}>{confirmed[l.product.id]?'✓ معتمد':'اعتماد الكمية'}</button>}</div>})}<div className="drawer-total"><span>الإجمالي</span><strong>{money(total)}</strong></div>{config.showPaymentMethods&&<div className="payment-box"><strong>طريقة الدفع</strong>{PAYMENT_OPTIONS.filter(x=>config[x.field]).map(x=><label key={x.key}><input type="radio" checked={payment===x.key} onChange={()=>setPayment(x.key)}/>{x.label}</label>)}</div>}{config.showTemplates&&<label className="template-inline"><input value={templateName} onChange={e=>setTemplateName(e.target.value)} placeholder="حفظ كقائمة"/><button disabled={!templateName.trim()||busy} onClick={()=>void saveTemplate()}>حفظ</button></label>}<button className="checkout" disabled={busy||!cart.length} onClick={()=>void submit()}>{busy?'جارٍ تنفيذ العملية…':'تأكيد وإرسال الطلب'}</button></aside></div>}
  </div>;
}

function QuickOrder({products,onAddMany}:{products:Product[];onAddMany:(items:Array<{product:Product;quantity:number}>)=>Promise<void>}){const [sku,setSku]=useState('');const [qty,setQty]=useState('1');const [file,setFile]=useState<File|null>(null);const [diagnostics,setDiagnostics]=useState<QuickOrderDiagnostic[]>([]);const [preview,setPreview]=useState<Array<{product:Product;quantity:number}>>([]);const [busy,setBusy]=useState(false);const found=products.find(p=>p.sku.toLowerCase()===sku.trim().toLowerCase());async function validateFile(next:File){setFile(next);setDiagnostics([]);setPreview([]);try{const rows=await parseQuickOrderWorkbook(next);const result=validateQuickOrderRows(rows,products);setDiagnostics(result.diagnostics);setPreview(result.valid.map(x=>({product:x.product,quantity:x.quantity})));}catch(e){setDiagnostics([{rowNumber:1,sku:'',quantity:0,message:e instanceof Error?e.message:'تعذر قراءة الملف.'}]);}}async function confirmFile(){if(!preview.length||diagnostics.length||busy)return;setBusy(true);try{await onAddMany(preview);setFile(null);setPreview([]);}catch(e){setDiagnostics([{rowNumber:1,sku:'',quantity:0,message:e instanceof Error?e.message:'تعذر إضافة الطلب السريع.'}]);}finally{setBusy(false);}}async function manualAdd(){if(!found)return;const quantity=Number(qty);if(!Number.isSafeInteger(quantity)||quantity<1||quantity>found.availableQuantity)return;setBusy(true);try{await onAddMany([{product:found,quantity}]);setSku('');setQty('1');}finally{setBusy(false);}}return <div className="quick-editor"><div className="quick-manual"><input value={sku} onChange={e=>setSku(e.target.value)} placeholder="SKU"/><input value={qty} onChange={e=>setQty(e.target.value)} type="number" min="1" placeholder="الكمية"/><button disabled={!found||busy} onClick={()=>void manualAdd()}>إضافة للسلة</button>{found&&<div className="quick-result">{found.name} · متاح {found.availableQuantity} {found.unit}</div>}</div><div className="quick-upload"><label className="file-button">{file?'تغيير ملف Excel':'اختيار ملف Excel'}<input type="file" accept=".xlsx" onChange={e=>{const next=e.target.files?.[0];if(next)void validateFile(next);}}/></label>{file&&<strong>{file.name}</strong>}</div>{preview.length>0&&<div className="quick-preview"><strong>المراجعة: {preview.length} سطر صالح</strong>{preview.map(item=><div key={item.product.id}>{item.product.sku} · {item.product.name} · {item.quantity}</div>)}<button disabled={busy||diagnostics.length>0} onClick={()=>void confirmFile()}>تأكيد وإضافة للسلة</button></div>}{diagnostics.length>0&&<div className="error-banner">{diagnostics.map((d,i)=><div key={`${d.rowNumber}-${i}`}>الصف {d.rowNumber}: {d.message}</div>)}</div>}</div>}
