import { useCallback, useEffect, useState } from 'react';
import { getCategories, type CategoryOption } from './services/categories';
import { upsertProduct, assertProductStatus } from './services/admin';
import { supabase } from './lib/supabase';

type UserRole='owner'|'admin'|'sales'|'warehouse'|'viewer';
type StaffProduct={id:string;sku:string;name:string;unit:string;category_id:string|null;description:string|null;status:'active'|'inactive'};

export default function ProductEditPanel({role}:{role:UserRole}){
  const canManage=['owner','admin','sales'].includes(role); if(!canManage)return null;
  const [products,setProducts]=useState<StaffProduct[]>([]); const [categories,setCategories]=useState<CategoryOption[]>([]); const [selectedId,setSelectedId]=useState(''); const [form,setForm]=useState({sku:'',name:'',unit:'كرتون',categoryId:'',description:'',status:'active' as 'active'|'inactive'}); const [busy,setBusy]=useState(false); const [error,setError]=useState<string|null>(null); const [message,setMessage]=useState<string|null>(null);
  const reload=useCallback(async()=>{if(!supabase)return;const [{data,error:pe},cats]=await Promise.all([supabase.from('products').select('id,sku,name,unit,category_id,description,status').order('name').limit(500),getCategories()]);if(pe)throw pe;setProducts((data??[]) as StaffProduct[]);setCategories(cats);},[]);
  useEffect(()=>{void reload().catch(e=>setError(e instanceof Error?e.message:'تعذر تحميل المنتجات.'));},[reload]);
  function choose(id:string){setSelectedId(id);const p=products.find(x=>x.id===id);if(p)setForm({sku:p.sku,name:p.name,unit:p.unit,categoryId:p.category_id??'',description:p.description??'',status:assertProductStatus(p.status)});}
  async function save(){setBusy(true);setError(null);setMessage(null);try{await upsertProduct({productId:selectedId||null,sku:form.sku,name:form.name,unit:form.unit,categoryId:form.categoryId||null,description:form.description||null,status:form.status});setMessage(selectedId?'تم تحديث المنتج.':'تم إنشاء المنتج.');setSelectedId('');setForm({sku:'',name:'',unit:'كرتون',categoryId:'',description:'',status:'active'});await reload();}catch(e){setError(e instanceof Error?e.message:'تعذر حفظ المنتج.');}finally{setBusy(false);}}
  return <section className="admin-card"><h3>تعديل / أرشفة المنتجات</h3><select aria-label="المنتج المراد تعديله" value={selectedId} onChange={e=>choose(e.target.value)}><option value="">منتج جديد</option>{products.map(p=><option key={p.id} value={p.id}>{p.name} · {p.sku}</option>)}</select><div className="admin-edit-grid"><input aria-label="SKU" placeholder="SKU" value={form.sku} onChange={e=>setForm({...form,sku:e.target.value})} required/><input aria-label="اسم المنتج" placeholder="اسم المنتج" value={form.name} onChange={e=>setForm({...form,name:e.target.value})} required/><input aria-label="الوحدة" placeholder="الوحدة" value={form.unit} onChange={e=>setForm({...form,unit:e.target.value})} required/><select aria-label="التصنيف" value={form.categoryId} onChange={e=>setForm({...form,categoryId:e.target.value})}><option value="">بدون تصنيف</option>{categories.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select><select aria-label="حالة المنتج" value={form.status} onChange={e=>setForm({...form,status:e.target.value as 'active'|'inactive'})}><option value="active">نشط</option><option value="inactive">موقوف / مؤرشف</option></select></div><textarea aria-label="وصف المنتج" placeholder="وصف المنتج" rows={3} value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/><button disabled={busy} onClick={()=>void save()}>{selectedId?'حفظ التعديل':'إنشاء المنتج'}</button>{selectedId&&<button className="ghost" disabled={busy} onClick={()=>choose('')}>إلغاء التعديل</button>}{error&&<div className="error-banner" role="alert">{error}</div>}{message&&<div className="success" role="status">{message}</div>}</section>;
}
