-- Retired legacy finance migration.
--
-- The original 0013 targeted the pre-operational `sales_invoices` / `companies`
-- model, which is not part of the canonical schema. Keeping those DDL statements
-- executable makes a clean-from-empty replay fail before the canonical operational
-- finance migration (0032) can create its authoritative tables.
--
-- Canonical finance is created by 0032_finance_invoices_cash_expenses.sql and
-- hardened by the subsequent finance migrations. This migration is intentionally
-- a no-op so historical ordering remains stable while clean replay remains valid.
